import addClass from './addClass';
import hasClass from './hasClass';
import isEdge from './isEdge';
import isFirefox from './isFirefox';
import isIE from './isIE';
import isNumber from './isNumber';
import isServer from './isServer';
import isString from './isString';
import removeClass from './removeClass';
declare const _default: {
    addClass: (el: HTMLElement, cls: string) => void;
    hasClass: (el: HTMLElement, cls: string) => boolean;
    isEdge: () => boolean;
    isFirefox: () => boolean;
    isIE: () => boolean;
    isNumber: (val: unknown) => boolean;
    isServer: () => boolean;
    isString: (val: unknown) => boolean;
    removeClass: (el: HTMLElement, cls: string) => void;
};
export default _default;
export { addClass, hasClass, isEdge, isFirefox, isIE, isNumber, isServer, isString, removeClass };
